// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJj23lR0mLqcSFK64pIdGBpYxSIjyrW44',
    appId: '1:847226591367:web:a4a2709af7c06a332f4022',
    messagingSenderId: '847226591367',
    projectId: 'evelynapp-932d3',
    authDomain: 'evelynapp-932d3.firebaseapp.com',
    storageBucket: 'evelynapp-932d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc0_f92mp5_Yp005B6_NOfczhRxgG3cYI',
    appId: '1:847226591367:android:e8aeea609cf0d7bf2f4022',
    messagingSenderId: '847226591367',
    projectId: 'evelynapp-932d3',
    storageBucket: 'evelynapp-932d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdDBky1uTlBFo4xUU1B1KxrQ0B1_GZz6c',
    appId: '1:847226591367:ios:f765471d1efc0e612f4022',
    messagingSenderId: '847226591367',
    projectId: 'evelynapp-932d3',
    storageBucket: 'evelynapp-932d3.appspot.com',
    iosClientId: '847226591367-ibr2tln41on4vpoamvak75ia1v2mu7el.apps.googleusercontent.com',
    iosBundleId: 'com.example.evelynapp',
  );
}
